VexRiscv:
	mill VexRiscv.runMain vexriscv.demo.GenFull

Briey:
	mill VexRiscv.runMain vexriscv.demo.Briey

Murax:
	mill VexRiscv.runMain vexriscv.demo.Murax

MuraxInit:
	mill VexRiscv.runMain vexriscv.demo.MuraxWithRamInit

testMurax:
	mill VexRiscv.test.runMain vexriscv.MuraxSim

.PHONY:VexRiscv Briey Murax testMurax MuraxInit

