-d /home/shaw/GW/IDE/bin/fpga_project/led_water/impl/gwsynthesis/led_water.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AC1/I0
-cst /home/shaw/GW/IDE/bin/fpga_project/led_water/src/led_water.cst
-cfg /home/shaw/GW/IDE/bin/fpga_project/led_water/impl/pnr/device.cfg
-bit
-tr
-ph
-timing
-cst_error
-correct_hold 1
-route_maxfan 23
